### ISSUE TITLE
uncaught NoSuchMethodError

### ISSUE THREAD

**Issue by Spazzze** [nekocode/android-parcelable-intellij-plugin-kotlin#14]
Hi guys,

this plugin worked pretty good for me before,
today I am getting this plugin crash while trying to generate parcelable code. 
This error occurs even when I try to regenerate code at existed classes.
I tried to clear cache and restart, clean project, reinstall plugin, degrade kotlin version, even new project. Nothing helps. 

Kotlin 1.0.5-2
Android Studio 2.2.3
Build #AI-145.3537739, built on December 2, 2016
JRE: 1.8.0_112-release-b05 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

```
Plugin Error: Parcelable Code Generator(for kotlin) threw an uncaught NoSuchMethodError. Disable Plugin
NoSuchMethodError: org.jetbrains.kotlin.descriptors.ClassDescriptor.getUnsubstitutedPrimaryConstructor()Lorg/jetbrains/kotlin/descriptors/ConstructorDescriptor;
```

**Comment by nekocode** [comment]
Thank's for the report! I'll check it.

**Comment by nekocode** [comment]
What's the version of your kotlin-plugin?

**Comment by Spazzze** [comment]
Kotlin 1.0.5-2

**Comment by zokipirlo** [comment]
I'm getting the same exception with kotlin 1.1 beta and Android Studio 2.3 beta 3

`org.jetbrains.kotlin.descriptors.ClassDescriptor.getUnsubstitutedPrimaryConstructor()Lorg/jetbrains/kotlin/descriptors/ConstructorDescriptor;
java.lang.NoSuchMethodError: org.jetbrains.kotlin.descriptors.ClassDescriptor.getUnsubstitutedPrimaryConstructor()Lorg/jetbrains/kotlin/descriptors/ConstructorDescriptor;
	at cn.nekocode.plugin.parcelablegenerator.utils.KtClassHelper.findParams(KtClassHelper.java:47)
	at cn.nekocode.plugin.parcelablegenerator.ParcelableAction.actionPerformed(ParcelableAction.java:53)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:875)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.lambda$onChosen$0(PopupFactoryImpl.java:863)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.ui.popup.AbstractPopup.lambda$null$7(AbstractPopup.java:1390)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:795)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by chantellosejo** [comment]
Ditto, seeing the same thing.

10:46:55 AM NoSuchMethodError: org.jetbrains.kotlin.descriptors.ClassDescriptor.getUnsubstitutedPrimaryConstructor()Lorg/jetbrains/kotlin/descriptors/ConstructorDescriptor;

**Comment by roschlau** [comment]
Me too, AS 2.2.2, Kotlin 1.1.0

**Comment by nambv** [comment]
Me too, Android Studio 2.3, Kotlin 1.1.0

**Comment by hackaprende** [comment]
Same here, Android 2.3, Kotlin 1.1.0, Plugin 0.6.0

**Comment by nekocode** [comment]
I will check it this weekend. Thanks for the report.

**Comment by nekocode** [comment]
Fixed: https://github.com/nekocode/android-parcelable-intellij-plugin-kotlin/releases/tag/0.6.1

**Comment by TigerHix** [comment]
@nekocode Doesn't seem to have a release jar included?

**Comment by nekocode** [comment]
@TigerHix Oh, i forgot it. Check it again~

**Comment by TigerHix** [comment]
^^ Thank you!

**Comment by Lans** [comment]
Kotlin 1.1.60 threw an uncaught NoSuchMethodError.
