### ISSUE TITLE
Plugin Exception

### ISSUE THREAD

**Issue by maarek** [nekocode/android-parcelable-intellij-plugin-kotlin#2]
Using Android Studio 1.5.1 and trying to install this plugin, all I get is the following exception which might have something to do with compiled version? 

```
cannot create class "cn.nekocode.plugin.parcelablegenerator.ParcelableAction" [Plugin:     cn.nekocode.plugin.parcelablegenerator]
com.intellij.diagnostic.PluginException: cannot create class "cn.nekocode.plugin.parcelablegenerator.ParcelableAction" [Plugin: cn.nekocode.plugin.parcelablegenerator]
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:178)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convert(ActionManagerImpl.java:518)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:498)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:491)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:354)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1323)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1316)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1316)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1310)
    at com.intellij.codeInsight.generation.actions.GenerateAction.preload(GenerateAction.java:99)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1328)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1331)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1310)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.doPreloadActions(ActionManagerImpl.java:1298)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.access$200(ActionManagerImpl.java:78)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$4.run(ActionManagerImpl.java:1281)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: com.intellij.diagnostic.PluginException: cn/nekocode/plugin/parcelablegenerator/ParcelableAction : Unsupported major.minor version 52.0 [Plugin: cn.nekocode.plugin.parcelablegenerator]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:154)
    ... 25 more
Caused by: java.lang.UnsupportedClassVersionError: cn/nekocode/plugin/parcelablegenerator/ParcelableAction : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
    ... 31 more
```

**Comment by nekocode** [comment]
It seams that you are using a lower version JDK eg. JDK 1.7.The simplest way to fix this issue is to install the lastest Java release. And I will try to compile this plugin for a lower JRE version.Thanks for your feedback~

**Comment by Gustik** [comment]
+1 May be publish 1.7 version in plugin repo?

**Comment by alexparra01** [comment]
I'm having this error Null child action in group Generate () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=generateParcelableKotlin

**Comment by nekocode** [comment]
Try about this release: **[Version 0.4.3](https://github.com/nekocode/android-parcelable-intellij-plugin-kotlin/releases/tag/v0.4.3)**
And feed back to me as possible.Thx~

@Gustik @alexparra01 @maarek

**Comment by alexparra01** [comment]
Now I got this error 
11:19:18 PM Plugin Error: Parcelable Code Generator(for kotlin's data class) threw an uncaught PluginException. Disable Plugin
11:19:18 PM PluginException: cannot create class "cn.nekocode.plugin.parcelablegenerator.ParcelableAction" [Plugin: cn.nekocode.plugin.parcelablegenerator]
11:19:45 PM EmptyThrowable: Null child action in group Generate () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=generateParcelableKotlin

**Comment by sosmolovskii** [comment]
I have this exception when i using code generation in Java class (IDEA 14.1.01674, java 1.7.0_79):

org/jetbrains/kotlin/psi/KtFile
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/psi/KtFile
	at cn.nekocode.plugin.parcelablegenerator.ParcelableAction.getPsiClassFromEvent(ParcelableAction.java:82)
	at cn.nekocode.plugin.parcelablegenerator.ParcelableAction.update(ParcelableAction.java:69)
	at com.intellij.openapi.actionSystem.AnAction.beforeActionPerformedUpdate(AnAction.java:243)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:111)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionStepBuilder.b(PopupFactoryImpl.java:934)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionStepBuilder.b(PopupFactoryImpl.java:924)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionStepBuilder.buildGroup(PopupFactoryImpl.java:860)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.a(PopupFactoryImpl.java:257)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:214)
	at com.intellij.ui.popup.PopupFactoryImpl.a(PopupFactoryImpl.java:194)
	at com.intellij.ui.popup.PopupFactoryImpl.a(PopupFactoryImpl.java:168)
	at com.intellij.ui.popup.PopupFactoryImpl.createActionGroupPopup(PopupFactoryImpl.java:296)
	at com.intellij.codeInsight.generation.actions.GenerateAction.actionPerformed(GenerateAction.java:38)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:586)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:637)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)



java.lang.NoClassDefFoundError: org/jetbrains/kotlin/psi/KtFile
	at cn.nekocode.plugin.parcelablegenerator.ParcelableAction.getPsiClassFromEvent(ParcelableAction.java:82)
	at cn.nekocode.plugin.parcelablegenerator.ParcelableAction.update(ParcelableAction.java:69)
	at com.intellij.openapi.actionSystem.AnAction.beforeActionPerformedUpdate(AnAction.java:243)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:111)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionStepBuilder.b(PopupFactoryImpl.java:934)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionStepBuilder.b(PopupFactoryImpl.java:924)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionStepBuilder.buildGroup(PopupFactoryImpl.java:860)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.a(PopupFactoryImpl.java:257)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:214)
	at com.intellij.ui.popup.PopupFactoryImpl.a(PopupFactoryImpl.java:194)
	at com.intellij.ui.popup.PopupFactoryImpl.a(PopupFactoryImpl.java:168)
	at com.intellij.ui.popup.PopupFactoryImpl.createActionGroupPopup(PopupFactoryImpl.java:296)
	at com.intellij.codeInsight.generation.actions.GenerateAction.actionPerformed(GenerateAction.java:38)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:586)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:637)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)



java.lang.NoClassDefFoundError: org/jetbrains/kotlin/psi/KtFile
	at cn.nekocode.plugin.parcelablegenerator.ParcelableAction.getPsiClassFromEvent(ParcelableAction.java:82)
	at cn.nekocode.plugin.parcelablegenerator.ParcelableAction.update(ParcelableAction.java:69)
	at com.intellij.openapi.actionSystem.AnAction.beforeActionPerformedUpdate(AnAction.java:243)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:111)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionStepBuilder.b(PopupFactoryImpl.java:934)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionStepBuilder.b(PopupFactoryImpl.java:924)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionStepBuilder.buildGroup(PopupFactoryImpl.java:860)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.a(PopupFactoryImpl.java:257)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:214)
	at com.intellij.ui.popup.PopupFactoryImpl.a(PopupFactoryImpl.java:194)
	at com.intellij.ui.popup.PopupFactoryImpl.a(PopupFactoryImpl.java:168)
	at com.intellij.ui.popup.PopupFactoryImpl.createActionGroupPopup(PopupFactoryImpl.java:296)
	at com.intellij.codeInsight.generation.actions.GenerateAction.actionPerformed(GenerateAction.java:38)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:586)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:637)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by kenyee** [comment]
FWIW, I saw this too...using Android Studio 2.1.2 w/ Java 1.8_102 JDK.

**Comment by nekocode** [comment]
@kenyee Can you tell me the version of your kotlin-plugin?

<img width="418" alt="2016-08-12 10 51 22" src="https://cloud.githubusercontent.com/assets/4783781/17626347/7cac0072-60df-11e6-962c-3aba515bbd32.png">

**Comment by kenyee** [comment]
kotlin parcelable plugin is 0.4.6 installed from Android Studio's plugin feature in preferences.

kotlin plugin says 1.0.3-release-ij143-105.  Android Studio keeps your plugins updated fairly well :-)

**Comment by BharathMG** [comment]
The original exception is happening to me as well. 

Java = JDK 1.8.0_102-b14 Latest version
Kotlin = 1.0.3-release-ij143-105
Kotlin Parcelable Plugin = 0.4.6
Studio = 2.1.2

Exception : Null child action in group Generate () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=generateParcelableKotlin
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:117)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:356)
    at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
    at com.intellij.openapi.actionSystem.ActionGroupUtil.isGroupEmpty(ActionGroupUtil.java:45)
    at com.intellij.openapi.actionSystem.ActionGroupUtil.isGroupEmpty(ActionGroupUtil.java:39)
    at com.intellij.codeInsight.generation.actions.GenerateAction.update(GenerateAction.java:65)
    at com.intellij.openapi.actionSystem.AnAction.beforeActionPerformedUpdate(AnAction.java:246)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:111)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:622)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:485)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by nekocode** [comment]
@maarek  @Gustik  @alexparra01  @kenyee  @BharathMG  Can you help me to try the [new version](https://github.com/nekocode/android-parcelable-intellij-plugin-kotlin/releases/download/0.4.7/android-parcelable-generator-kotlin.jar)? I rebuilt it with java6.

**Comment by nekocode** [comment]
I'm sure the new version have fixed this issue now.

**Comment by nekocode** [comment]
The exception happens when your IDE is using JDK6. See this: http://tools.android.com/tech-docs/configuration/osx-jdk
